version: '3.8'

services:
  db:
    container_name: postgres-node
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${TYPEORM_USERNAME}
      - POSTGRES_PASSWORD=${TYPEORM_PASSWORD}
      - POSTGRES_DB=${TYPEORM_DATABASE}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
  api:
    build:
      dockerfile: Dockerfile
      context: .
      target: production
    env_file:
      - .env
    ports:
      - 4000:4000
    depends_on:
      - db

volumes:
  pgdata:
